package modelo;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Instalacion generated by hbm2java
 */
@Entity
@Table(name = "instalacion", catalog = "proteccioncivil")
public class Instalacion implements java.io.Serializable {

	private Integer codparque;
	private String nombre;
	private String telefono;
	private String direccion;

	public Instalacion() {
	}

	public Instalacion(String nombre, String telefono, String direccion) {
		this.nombre = nombre;
		this.telefono = telefono;
		this.direccion = direccion;
	}
	
	public Instalacion(int codparque) {
		this.codparque = codparque;
		
	}
	public Instalacion(int codparque, String nombre, String telefono, String direccion) {
		this.codparque = codparque;
		this.nombre = nombre;
		this.telefono = telefono;
		this.direccion = direccion;
		
	}
	
	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "codparque", unique = true, nullable = false)
	public Integer getCodparque() {
		return this.codparque;
	}

	public void setCodparque(Integer codparque) {
		this.codparque = codparque;
	}

	@Column(name = "nombre", nullable = false, length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "telefono", nullable = false, length = 45)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "direccion", nullable = false, length = 45)
	public String getDireccion() {
		return this.direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}
	
	public String toString(){
		String aux ="";
		
		aux += "------------------------------------------";
		aux += "\n	CODIGO: " + this.codparque;
		aux += "\n	NOMBRE: " + this.nombre;
		aux += "\n	TELEFONO: " + this.telefono;
		aux += "\n	DIRECCION: " + this.direccion;
		aux += "\n------------------------------------------";
		
		return aux;
	}

}
